version: "3.7"

services:
    traefik:
        image: traefik:v2.5
        container_name: '${DOCKER_NAME}_traefik'
        command:
            - --log.level=DEBUG
            - --api.insecure=false
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.${TRAEFIK_ENTRYPOINT}.address=:80
            - --providers.docker
            - --api
            - --providers.file.filename=/root/.config/ssl.toml
            - --entrypoints.${TRAEFIK_ENTRYPOINT}.http.redirections.entryPoint.to=${TRAEFIK_SECURE_ENTRYPOINT}
            - --entrypoints.${TRAEFIK_ENTRYPOINT}.http.redirections.entryPoint.scheme=https
            - --entrypoints.${TRAEFIK_ENTRYPOINT}.http.redirections.entrypoint.permanent=true
            - --entrypoints.${TRAEFIK_SECURE_ENTRYPOINT}.address=:443
        restart: always
        networks:
            - ${TRAEFIK_NETWORK}
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik-ssl.toml:/root/.config/ssl.toml
            - ./certs/:/certs/
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.traefik.rule=Host(`${DOCKER_BASE_URL}`)'
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.entrypoints=${TRAEFIK_SECURE_ENTRYPOINT}"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
            - 'traefik.http.routers.traefik.tls=true'

    # smtp4dev:
    #     container_name: '${DOCKER_NAME}_smtp4dev'
    #     image: rnwood/smtp4dev:v3
    #     restart: unless-stopped
    #     ports:
    #         - '3000:80'
    #         - '25:25'
    #     volumes:
    #         - smtp4dev-data:/smtp4dev
    #     networks:
    #         - traefik
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.services.${DOCKER_NAME}_smtp4dev.loadbalancer.server.port=80"
    #         - "traefik.http.routers.${DOCKER_NAME}-smtp4dev.rule=Host(`smtp4dev.${DOCKER_BASE_URL}`)"
    #         - "traefik.http.routers.${DOCKER_NAME}-smtp4dev.service=${DOCKER_NAME}_smtp4dev"
    #         - "traefik.http.routers.${DOCKER_NAME}-smtp4dev.entrypoints=${TRAEFIK_SECURE_ENTRYPOINT}"
    #         - 'traefik.http.routers.${DOCKER_NAME}-smtp4dev.tls=true'
    #         - "traefik.docker.network=traefik"

    portainer:
        image: portainer/portainer
        container_name: "${DOCKER_NAME}_portainer"
        command: --no-auth -H unix:///var/run/docker.sock
        restart: unless-stopped
        networks:
            - traefik
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${DOCKER_NAME}_portainer.loadbalancer.server.port=80"
            - "traefik.http.routers.${DOCKER_NAME}-portainer.rule=Host(`portainer.${DOCKER_BASE_URL}`)"
            - "traefik.http.routers.${DOCKER_NAME}-portainer.service=${DOCKER_NAME}_portainer"
            - "traefik.http.routers.${DOCKER_NAME}-portainer.entrypoints=${TRAEFIK_SECURE_ENTRYPOINT}"
            - 'traefik.http.routers.${DOCKER_NAME}-portainer.tls=true'
            - "traefik.docker.network=${TRAEFIK_NETWORK}"

networks:
    ${TRAEFIK_NETWORK}:
        external: true
